Art assets
UnityTechnologies/open-project-1 pull request #142
Opened 2020-11-03 10:20 UTC by recklol

Forum thread:
https://forum.unity.com/threads/burn-disappear-effect.997856/
Card:
https://open.codecks.io/unity-open-project-1/decks/24/card/176-burn-disappear-effect

This is a basic, stylized implementation of a dissolve effect. A shader and a Particle System working together. 
These changes are important to give feedback to the player, and also feel satisfying to look at.
I implemented it the best way I could, making it customizable easily.

2020-11-03 10:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/UnityTechnologies/open-project-1?pullRequest=142) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/UnityTechnologies/open-project-1?pullRequest=142) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/UnityTechnologies/open-project-1?pullRequest=142) it.</sub>

2020-11-03 10:43 UTC, ciro-unity requested changes
Great PR, but there are a few files which I don't think belong in it. I understand the need to demo the effect in the art scene, but you can keep it in that one so it doesn't conflict with changes on other scenes.

Can you strip everything that is not absolutely necessary? Thanks!

2020-11-03 10:43 UTC, ciro-unity commented on .gitignore
> +UOP1_Project/ProjectSettings/URPProjectSettings.asset
Why would you want to ignore all these?

2020-11-03 10:43 UTC, ciro-unity commented on UOP1_Project/Assets/Scenes/CharController.unity
>    m_Children:
Why all the changes in this file?

2020-11-08 10:20 UTC, closed without merging

2020-11-08 10:47 UTC, ciro-unity commented
Hope everything is good with this one! Come ask for help on the forums if you're having trouble with Git?

2020-11-08 10:53 UTC, recklol commented
I messed up my local repo AND also had other problems with my computer. I made another branch, where I have a clean commit with only the necessary files.

Should I make a new pullrequest from that?

2020-11-25 13:58 UTC, treivize commented
Hello @recklol,

Just to let you know that to progress on delivering your dissolve effect I have opened a new PR to bring it back on an the current code stack. Please do not hesitate to review my changes and let me know if you are fine or now with them.
[new PR](https://github.com/UnityTechnologies/open-project-1/pull/217)