Custom timeline track and clip for dialog
UnityTechnologies/open-project-1 pull request #64
Opened 2020-10-04 20:35 UTC by Caiuse

- Custom timeline track and clip
- Each clip has settings which using the `text` option as a ID for the line of dialog needed to be displayed
- Each track can has a binder assigned which can later be inherited to build the logic for binding text to the screen.
- If `pauseAndWaitForInput` clip option is selected the graph will pause and wait for another system to unpause the graph.

2020-10-04 20:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/UnityTechnologies/open-project-1?pullRequest=64) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/UnityTechnologies/open-project-1?pullRequest=64) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/UnityTechnologies/open-project-1?pullRequest=64) it.</sub>

2020-10-05 12:25 UTC, dkaloger requested changes
overlap with https://github.com/UnityTechnologies/open-project-1/pull/56

2020-10-06 04:54 UTC, Caiuse commented
Used @Aspekt1024 dialog track as the base on this PR and adapted the functionality after talking with him. 

@dkaloger reviewed your PR, once those bits have been addressed we can raise another PR which merges your rendering. These two systems can remain decoupled for the moment making Unity's review a little easier 🤞

2020-10-16 12:44 UTC, 0479010347 approved these changes

2020-10-16 12:46 UTC, 0479010347 commented
What is this

2020-10-16 12:55 UTC, ardaozler commented
I didnt mean to issue a pull req. I must have done it by accident. Sorry! 

Android’de Yahoo Postadan gönderildi 
 
  15:47’’16e’ 16 Eki 2020 Cum tarihinde, 0479010347<notifications@github.com> şunu yazdı:   


What is this

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-10-16 12:56 UTC, ardaozler commented
I just realized that i recieved this because im on watch sorry again lol.

Android’de Yahoo Postadan gönderildi 
 
  15:55’’16e’ 16 Eki 2020 Cum tarihinde, Arda Özler<ardaozler@yahoo.com> şunu yazdı:   I didnt mean to issue a pull req. I must have done it by accident. Sorry! 

Android’de Yahoo Postadan gönderildi 
 
  15:47’’16e’ 16 Eki 2020 Cum tarihinde, 0479010347<notifications@github.com> şunu yazdı:   


What is this

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-11-01 00:11 UTC, ciro-unity requested changes
A nice start and thanks for making it short, but there are some things I'd like to fix before pulling it.

2020-11-01 00:11 UTC, ciro-unity commented on .editorconfig
> +csharp_using_directive_placement = outside_namespace
Why is this file part of the PR?

2020-11-01 00:11 UTC, ciro-unity commented on UOP1_Project/Assets/Scripts/Cutscenes/DialogueTimeline/DialogueMixerBehaviour.cs
> +		}
Are you looking just to know which clip is currently played by the Timeline? You should use weights.

@rainaldisatria is doing it here for instance: https://github.com/UnityTechnologies/open-project-1/blob/c1aca3610d73fa83acb43e72e895f349c4250fbf/UOP1_Project/Assets/Scripts/Cutscenes/Dialogue%20Timeline/DialogueControlMix.cs

If the weight is 0, the clip is not being played. If it's 1, it's played and it's the only one.
More than one clip can be played at a time due to a blend. In which case the weight won't be 1 but something in between.

2020-11-01 00:11 UTC, ciro-unity commented on UOP1_Project/Assets/Scripts/Cutscenes/DialogueTimeline/DialogueBinder.cs
> +		public abstract void SetDialog(string dialogueLineID);
The idea of calling a dialogue line from a ScriptableObject using a string sounds like a dangerous idea, it's prone to mistakes and doesn't work well when you decide to move lines around. Now you need to manually go and look into clips to change the IDs.

2020-11-06 01:08 UTC, ciro-unity commented
Closing because in the end I merged PR #135, with some code from this one too.

2020-11-06 01:08 UTC, closed without merging